### ISSUE TITLE
strToNum decoder does not support negative numbers

### ISSUE THREAD

**Issue by emadgit** [gordonmleigh/decoders#1]
Hi @gordonmleigh, 

it seems the regex used for strToNum decoder does not consider a negative number as an valid number, probably updating the regex to something like `/^-?\d+(\.(\d*))?$/` should allow negative numbers as well.

https://github.com/futurematik/decoders/blob/f393e3f11a666490ef2244d99c218a3fd2b0b46f/src/converters/strToNum.ts#L27

Cheers

**Comment by gordonmleigh** [comment]
Thanks for the report @emadgit. Fixed in 0.5.5. Let me know if you want it backported to another minor version.
